# This is a basic workflow to help you get started with Actions

name: SSFRP

# Controls when the workflow will run
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: 安装
        run: |
          wget https://static.openfrp.net/client/OpenFRP_0.47.1_3bc7ee63_20230225/frpc_linux_amd64.tar.gz
          tar -zxf frpc_linux_amd64.tar.gz
          mv frpc_linux_amd64 frpc
          sudo chmod +x frpc
          sudo apt-get install openssh-server
          pip install youtube-dl

      - name: 配置
        run: |          
          #配置FRP
          
          touch frp.ini
          cat >> frp.ini <<EOF
          [common]
          server_addr = ${{ secrets.OP_FRPC_SERVER }}
          server_port = 8120
          protocol = tcp
          tls_enable = true
          user = ${{ secrets.OP_FRPC_USER }}
          token = ${{ secrets.OP_FRPC_TOKEN }}

          [TEST1]
          type = tcp
          local_ip = 127.0.0.1
          local_port = 1888
          remote_port = 40097
          use_encryption = true
          use_compression = true
          EOF
          sed -i 's/^[ \t]*//g' ./frp.ini
          
          #配置SSH
          cat >> ~/ssh/sshd_config <<EOF
          Port 1888
          PermitRootLogin yes
          PubkeyAuthentication yes
          EOF
          sed -i 's/^[ \t]*//g' ~/ssh/sshd_config
          
          echo ${{ secrets.SSH_KEY }} >> ~/.ssh/authorized_keys

      - name: 启动
        run: |          
          #启动SSH
          sudo /usr/sbin/sshd -f ~/ssh/sshd_config
          sudo service sshd restart
          
          #启动FRP
          ./frpc -c frp.ini
